name: Atualiza badge do Desafio Final

on:
  push:
    branches:
      - main
    paths:
      - "exercicios/desafio_final/**"
      - ".github/workflows/coverage_badge_desafio_final.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instala Poetry
        run: pipx install poetry

      - name: Instala dependências
        working-directory: exercicios/desafio_final
        run: poetry install

      - name: Executa testes e gera badge
        working-directory: exercicios/desafio_final
        run: |
          echo "==== INICIANDO A EXECUÇÃO DOS TESTES ===="
          
          # Executa o pytest direto na condição. Se falhar 1 teste, vai pro ELSE.
          if PYTHONPATH=. poetry run pytest tests/test_.py; then
            echo "==== RESULTADO: SUCESSO! Todos os testes passaram. ===="
            STATUS="4%2F4"
            COLOR="brightgreen"
          else
            echo "==== RESULTADO: FALHA! Pelo menos um teste quebrou. ===="
            STATUS="0%2F4"
            COLOR="red"
          fi

          echo "==== VARIÁVEIS DEFINIDAS: Status -> $STATUS | Cor -> $COLOR ===="
          
          curl -o tests.svg "https://img.shields.io/badge/desafio%20final-${STATUS}-${COLOR}"
          echo "==== BADGE BAIXADA DO SHIELDS.IO ===="

      - name: Verifica se a badge foi gerada
        working-directory: exercicios/desafio_final
        run: test -f tests.svg

      - name: Prepara diretório para publicação
        run: |
          mkdir badge
          cp exercicios/desafio_final/tests.svg badge/desafio-final.svg

      - name: Publica badge
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: badge-desafio-final
          publish_dir: badge
          force_orphan: true